---
abstract: 'Schema for publikacnicislo.cz application.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Schema-PublikacniCislo
no_index:
  directory:
    - inc
    - share
    - t
    - xt
requires:
  DBIx::Class::Core: 0
  DBIx::Class::InflateColumn::DateTime: 0
  DBIx::Class::Schema: 0
  File::Share: 0
  Schema::Abstract: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/commons-vote/Schema-PublikacniCislo/issues
  homepage: https://github.com/commons-vote/Schema-PublikacniCislo
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/commons-vote/Schema-PublikacniCislo
version: '0.01'
